import 'reflect-metadata';
import { DataSource } from 'typeorm';
import {
  ActionConfig,
  Branch,
  Customer,
  CustomerAssignee,
  Department,
  DetailViewTemplate,
  DispatchRule,
  DispatchedOrder,
  ExceptionModuleHandler,
  DispatchedOrderReturnRecord,
  ExportTemplate,
  FieldConfig,
  FieldPermission,
  FieldSupplementLog,
  FieldSupplementRule,
  ImportJob,
  ImportTemplateField,
  InServiceOrder,
  ModuleField,
  ModuleHandler,
  ModuleHandlerDelegation,
  ModuleSupervisor,
  Notification,
  OperationLog,
  OutOfProvinceOrder,
  Role,
  User,
  UserRole,
  WorkOrder,
  WorkOrderFieldDirtyMark,
  WorkOrderFieldSyncBatch,
  WorkOrderFieldSyncItem,
  WorkOrderModuleConfig,
  WorkflowDefinition,
} from 'src/entities';

const isTsRuntime = __filename.endsWith('.ts');

const AppDataSource = new DataSource({
  type: 'postgres',
  host: process.env.DB_HOST ?? '127.0.0.1',
  port: Number(process.env.DB_PORT ?? 5432),
  username: process.env.DB_USERNAME ?? 'postgres',
  password: process.env.DB_PASSWORD ?? 'postgres',
  database: process.env.DB_DATABASE ?? 'ticket_system',
  schema: process.env.DB_SCHEMA ?? 'public',
  synchronize: false,
  logging: (process.env.DB_LOGGING ?? 'false') === 'true',
  entities: [
    ActionConfig,
    Branch,
    Customer,
    CustomerAssignee,
    Department,
    DetailViewTemplate,
    DispatchRule,
    DispatchedOrder,
    ExceptionModuleHandler,
    DispatchedOrderReturnRecord,
    ExportTemplate,
    FieldConfig,
    FieldPermission,
    FieldSupplementLog,
    FieldSupplementRule,
    ImportJob,
    ImportTemplateField,
    InServiceOrder,
    ModuleField,
    ModuleHandler,
    ModuleHandlerDelegation,
    ModuleSupervisor,
    Notification,
    OperationLog,
    OutOfProvinceOrder,
    Role,
    User,
    UserRole,
    WorkOrder,
    WorkOrderFieldDirtyMark,
    WorkOrderFieldSyncBatch,
    WorkOrderFieldSyncItem,
    WorkOrderModuleConfig,
    WorkflowDefinition,
  ],
  migrations: [isTsRuntime ? 'src/database/migrations/*.ts' : 'dist/database/migrations/*.js'],
});

export default AppDataSource;
