export type FundRatioMode = 'same' | 'separate';

export interface ContractSubjectFundRule {
  socialCreditCode: string;
  fundRatioOptions: string[];
  supplementaryFundRatioOptions: string[];
  fundRatioMode: FundRatioMode;
}

const sameRatio = (values: number[]): string[] => values.map((value) => `${value}%+${value}%`);
const fullSameRatio = sameRatio([5, 6, 7, 8, 9, 10, 11, 12]);

export const CONTRACT_SUBJECT_FUND_RULES: ContractSubjectFundRule[] = [
  { socialCreditCode: '91330206MAEM8K1J2T', fundRatioOptions: sameRatio([5, 8, 12]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91110105MAENTDM58T', fundRatioOptions: sameRatio([5]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91510105MAEPKQTR0R', fundRatioOptions: fullSameRatio, supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91310101MAEQEP1150', fundRatioOptions: sameRatio([5]), supplementaryFundRatioOptions: sameRatio([2, 3]), fundRatioMode: 'same' },
  { socialCreditCode: '91500103MAER6MW974', fundRatioOptions: sameRatio([5, 7, 8, 9, 10, 12]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91330106MAEN753A6T', fundRatioOptions: sameRatio([5]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91330106MAEQ5PGA59', fundRatioOptions: sameRatio([12]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91420103MAEQY72X3C', fundRatioOptions: sameRatio([5, 7, 8, 12]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91410100MAETJ59F69', fundRatioOptions: sameRatio([5]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91610103MAETE9Q218', fundRatioOptions: sameRatio([5]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91130101MAETT36R4E', fundRatioOptions: sameRatio([5]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91430103MAEWAYFJX5', fundRatioOptions: sameRatio([5, 8, 12]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91360102MAER321X5M', fundRatioOptions: sameRatio([5]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91530103MAEU7K3P6C', fundRatioOptions: sameRatio([5]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91230103MAEW3PUR89', fundRatioOptions: sameRatio([5]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91440104MAEWCWHD91', fundRatioOptions: fullSameRatio, supplementaryFundRatioOptions: [], fundRatioMode: 'separate' },
  { socialCreditCode: '91210202MAEW6A1C6R', fundRatioOptions: sameRatio([5]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91140105MAEX9CCB0Q', fundRatioOptions: sameRatio([5]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91440300MAEWGWN61W', fundRatioOptions: fullSameRatio, supplementaryFundRatioOptions: [], fundRatioMode: 'separate' },
  { socialCreditCode: '91370203MAG0RY4Q4N', fundRatioOptions: sameRatio([5]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91210102MAEWXWA37M', fundRatioOptions: sameRatio([5, 7, 8, 9, 10, 11, 12]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91370100MAEXGBMC86', fundRatioOptions: sameRatio([5]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91350102MAEWX2F02T', fundRatioOptions: sameRatio([5]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91120101MA82METN4E', fundRatioOptions: sameRatio([5]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91350203MAG1X020XG', fundRatioOptions: sameRatio([5]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91420607MAK2TA3G0U', fundRatioOptions: sameRatio([8]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91140802MAK1UQKG7W', fundRatioOptions: sameRatio([5]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91140491MAK2TX345N', fundRatioOptions: sameRatio([5]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91321202MAK29DU351', fundRatioOptions: sameRatio([5]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91320508MAK6F3QH3J', fundRatioOptions: sameRatio([5, 8, 10, 12]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91340103MAK6FXXW2E', fundRatioOptions: sameRatio([8]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91520115MAKAJH7A91', fundRatioOptions: sameRatio([5, 12]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91320213MAK750HT28', fundRatioOptions: fullSameRatio, supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91320691MAK668409U', fundRatioOptions: sameRatio([5, 8, 10]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91320583MAK4C7NC6F', fundRatioOptions: sameRatio([5, 8]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91320594MAK7ATQQ17', fundRatioOptions: fullSameRatio, supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91310101MAK9940Q47', fundRatioOptions: sameRatio([7]), supplementaryFundRatioOptions: sameRatio([5]), fundRatioMode: 'same' },
  { socialCreditCode: '91450102MAK7AFWB90', fundRatioOptions: sameRatio([5, 12]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91220103MAK6HWRL2Q', fundRatioOptions: fullSameRatio, supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91320104MAK9M3J943', fundRatioOptions: fullSameRatio, supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91320585MAK964AD5Y', fundRatioOptions: sameRatio([5, 8, 12]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91440604MAKHR1EQ0D', fundRatioOptions: sameRatio([5]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91620102MAKDE7X35N', fundRatioOptions: sameRatio([5]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91340800MAKA9QQ163', fundRatioOptions: sameRatio([5]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91320303MAKBHGHWXE', fundRatioOptions: fullSameRatio, supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91321002MAKAQUGB8P', fundRatioOptions: sameRatio([5, 12]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91320903MAK9A6E28W', fundRatioOptions: sameRatio([5]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91321192MAK9JH925L', fundRatioOptions: sameRatio([5]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91321311MAKB3L6H4N', fundRatioOptions: sameRatio([5]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91320485MAK9C3E8XW', fundRatioOptions: sameRatio([5, 12]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91320891MAK8ENKFX1', fundRatioOptions: sameRatio([5, 7, 10]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91341002MAK94PDUX6', fundRatioOptions: sameRatio([5]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91340207MAKAKCG81A', fundRatioOptions: sameRatio([5, 10]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
  { socialCreditCode: '91110101MAKC73UW35', fundRatioOptions: sameRatio([12]), supplementaryFundRatioOptions: [], fundRatioMode: 'same' },
];

export const PAYROLL_LOCATIONS = [
  '北仑杭州分发薪',
  '北仑杭州西湖分发薪',
  '北仑北京分发薪',
  '北仑上海分发薪',
  '北仑武汉分发薪',
  '北仑成都分发薪',
  '北仑重庆分发薪',
  '北仑郑州分发薪',
  '北仑南昌分发薪',
  '北仑西安分发薪',
  '北仑长沙分发薪',
  '北仑石家庄分发薪',
  '北仑太原分发薪',
  '北仑昆明分发薪',
  '北仑哈尔滨分发薪',
  '北仑深圳分发薪',
  '北仑广州分发薪',
  '北仑青岛分发薪',
  '北仑济南分发薪',
  '北仑大连分发薪',
  '北仑福州分发薪',
  '北仑沈阳分发薪',
  '北仑天津分发薪',
  '北仑厦门分发薪',
  '北仑运城分发薪',
  '北仑襄阳分发薪',
  '北仑长治分发薪',
  '北仑泰州分发薪',
  '北仑昆山分发薪',
  '北仑苏州分发薪',
  '北仑长春分发薪',
  '北仑南宁分发薪',
  '北仑南通分发薪',
  '北仑苏州园区分发薪',
  '北仑合肥分发薪',
  '北仑无锡分发薪',
  '北仑上海黄浦分发薪',
  '北仑南京分发薪',
  '北仑太仓分发薪',
  '北仑淮安分发薪',
  '北仑盐城分发薪',
  '北仑常州分发薪',
  '北仑镇江分发薪',
  '北仑安庆分发薪',
  '北仑黄山分发薪',
  '北仑扬州分发薪',
  '北仑阜阳分发薪',
  '北仑宿迁分发薪',
  '北仑徐州分发薪',
  '北仑连云港分发薪',
  '北仑淮南分发薪',
  '北仑贵阳分发薪',
  '北仑芜湖分发薪',
  '北仑宿州分发薪',
  '北仑铜陵分发薪',
  '北仑蚌埠分发薪',
  '北仑兰州分发薪',
  '北仑呼和浩特分发薪',
  '北仑乌鲁木齐分发薪',
  '北仑海口分发薪',
  '北仑北京东城分发薪',
  '北仑鞍山分发薪',
  '北仑营口分发薪',
  '北仑佛山分发薪',
  '北仑济南历下分发薪',
  '北仑泰安分发薪',
  '北仑总发薪',
] as const;
